### ISSUE TITLE
Install package

### ISSUE THREAD

**Issue by vkummer** [dselivanov/rsparse#17]
Hi, I wanted to install the package using devtools::install_github("dselivanov/rsparse") but the installation always fails. The error it shows is: 

ERROR: dependency ‘float’ is not available for package ‘rsparse’ 

How can I fix this?

**Comment by dselivanov** [comment]
Try devtools::install_github("dselivanov/float") and then install rsparse.

ср, 25 апр. 2018 г., 9:30 vkummer <notifications@github.com>:

**Comment by vkummer** [comment]
Thank you for your prompt reply. Couldn't install float though, here are the error messages I get:

ERROR: configuration failed for package ‘float’

C compiler cannot create executables

**Comment by dselivanov** [comment]
Not sure why. Please provide `sessionInfo` and configure installation log.

ср, 25 апр. 2018 г., 9:54 vkummer <notifications@github.com>:

**Comment by vkummer** [comment]
> sessionInfo
function (package = NULL) 
{
    z <- list()
    z$R.version <- R.Version()
    z$platform <- z$R.version$platform
    if (nzchar(.Platform$r_arch)) 
        z$platform <- paste(z$platform, .Platform$r_arch, sep = "/")
    z$platform <- paste0(z$platform, " (", 8 * .Machine$sizeof.pointer, 
        "-bit)")
    z$locale <- Sys.getlocale()
    if (.Platform$OS.type == "windows") {
        z$running <- win.version()
    }
    else if (nzchar(Sys.which("uname"))) {
        uname <- system("uname -a", intern = TRUE)
        os <- sub(" .*", "", uname)
        z$running <- switch(os, Linux = if (file.exists("/etc/os-release")) {
            tmp <- readLines("/etc/os-release")
            t2 <- if (any(startsWith(tmp, "PRETTY_NAME="))) sub("^PRETTY_NAME=", 
                "", grep("^PRETTY_NAME=", tmp, value = TRUE)[1L]) else if (any(startsWith(tmp, 
                "NAME"))) sub("^NAME=", "", grep("^NAME=", tmp, 
                value = TRUE)[1L]) else "Linux (unknown distro)"
            sub("\"(.*)\"", "\\1", t2)
        } else if (file.exists("/etc/system-release")) {
            readLines("/etc/system-release")
        }, Darwin = {
            ver <- readLines("/System/Library/CoreServices/SystemVersion.plist")
            ind <- grep("ProductUserVisibleVersion", ver)
            ver <- ver[ind + 1L]
            ver <- sub(".*<string>", "", ver)
            ver <- sub("</string>$", "", ver)
            ver1 <- strsplit(ver, ".", fixed = TRUE)[[1L]][2L]
            sprintf("%s %s %s", ifelse(as.numeric(ver1) < 12, 
                "OS X", "macOS"), switch(ver1, `6` = "Snow Leopard", 
                `7` = "Lion", `8` = "Mountain Lion", `9` = "Mavericks", 
                `10` = "Yosemite", `11` = "El Capitan", `12` = "Sierra", 
                `13` = "High Sierra", ""), ver)
        }, SunOS = {
            ver <- system("uname -r", intern = TRUE)
            paste("Solaris", strsplit(ver, ".", fixed = TRUE)[[1L]][2L])
        }, uname)
    }
    if (is.null(package)) {
        package <- grep("^package:", search(), value = TRUE)
        keep <- vapply(package, function(x) x == "package:base" || 
            !is.null(attr(as.environment(x), "path")), NA)
        package <- .rmpkg(package[keep])
    }
    pkgDesc <- lapply(package, packageDescription, encoding = NA)
    if (length(package) == 0) 
        stop("no valid packages were specified")
    basePkgs <- sapply(pkgDesc, function(x) !is.null(x$Priority) && 
        x$Priority == "base")
    z$basePkgs <- package[basePkgs]
    if (any(!basePkgs)) {
        z$otherPkgs <- pkgDesc[!basePkgs]
        names(z$otherPkgs) <- package[!basePkgs]
    }
    loadedOnly <- loadedNamespaces()
    loadedOnly <- loadedOnly[!(loadedOnly %in% package)]
    if (length(loadedOnly)) {
        names(loadedOnly) <- loadedOnly
        pkgDesc <- c(pkgDesc, lapply(loadedOnly, packageDescription))
        z$loadedOnly <- pkgDesc[loadedOnly]
    }
    z$matprod <- as.character(options("matprod"))
    es <- extSoftVersion()
    z$BLAS <- as.character(es["BLAS"])
    z$LAPACK <- La_library()
    class(z) <- "sessionInfo"
    z
}
<bytecode: 0x7fd6d44d6a30>
<environment: namespace:utils>

**Comment by dselivanov** [comment]
`sessionInfo()` call :-)

ср, 25 апр. 2018 г., 10:11 vkummer <notifications@github.com>:

**Comment by dselivanov** [comment]
strange - I also use R 3.4.4 on OS X. What does installation of `float` say? Could you provide full installation log ?

**Comment by avivbrokman** [comment]
I'd like to try out your factorization machine R code, to share with my class, but I'm also unable to install `float`. I am including the two things you requested from 'vkummer': the installation log and 'sessionInfo()` 

FULL INSTALLATION LOG:

> devtools::install_github("dselivanov/float")
Downloading GitHub repo dselivanov/float@master
from URL https://api.github.com/repos/dselivanov/float/zipball/master
Installing float
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/mc/r7wbwryj10d3lybv8ctp47ww0000gn/T/RtmpUQfk2C/devtools39a049d0ecd6/dselivanov-float-1e09d8b'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘float’ ...
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... none needed
checking for sinf in -lm... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking size of int... 4
checking for echo... yes
checking for grep... yes
checking for sgemm_ in -lRblas... no
checking for sgetrf_ in -lRblas... no
checking for sgetrf_ in -lRlapack... no
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for gfortran... no
checking for g95... no
checking for xlf95... no
checking for f95... no
checking for fort... no
checking for ifort... no
checking for ifc... no
checking for efc... no
checking for pgfortran... no
checking for pgf95... no
checking for lf95... no
checking for ftn... no
checking for nagfor... no
checking whether we are using the GNU Fortran 77 compiler... no
checking whether  accepts -g... no
 
******************** Results of spm package configure *******************
 
* using 'int' for internal float storage
* NOTE: using package's single precision blas
  >> BLAS_LIBS=-L/Library/Frameworks/R.framework/Resources/lib -lRblas
* NOTE: using package's single precision lapack
  >> LAPACK_LIBS=-L/Library/Frameworks/R.framework/Resources/lib -lRlapack

The internal single precision BLAS are inefficient. Please consider installing high performance implementations, such as OpenBLAS (open source software) or MKL (available for free from the Microsoft R Open R distribution).

If you believe you are seeing this message in error, please contact the package maintainer.
  
*************************************************************************
 
configure: creating ./config.status
config.status: creating src/endianness.h
configure: creating ./config.status
config.status: creating src/endianness.h
config.status: creating src/Makevars
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include  -fopenmp -I../inst/include/ -fPIC  -Wall -g -O2  -c backsolve.c -o backsolve.o
clang: error: unsupported option '-fopenmp'
make: *** [backsolve.o] Error 1
ERROR: compilation failed for package ‘float’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/float’
Installation failed: Command failed (1)

SESSION INFO():

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.12.16    devtools_1.13.5 mlapi_0.1.0    

loaded via a namespace (and not attached):
 [1] httr_1.3.1     compiler_3.4.2 R6_2.2.2       tools_3.4.2    withr_2.1.2    rstudioapi_0.7
 [7] curl_3.1       memoise_1.1.0  knitr_1.17     git2r_0.21.0   digest_0.6.12

**Comment by dselivanov** [comment]
@avivbrokman please install clang with openmp support - check instructions [here](https://github.com/coatless/r-macos-rtools#how-do-i-use-the-installer).

**Comment by dselivanov** [comment]
@vkummer @avivbrokman I've removed `float` from dependencies and made robust configure script to identify OpenMP, BLAS, LAPACK. I believe now package can be easily installed with `devtools::install_github("dselivanov/rsparse")`. Please try and report if this doesn't work.

**Comment by vkummer** [comment]
@dselivanov I tried to run `devtools::install_github("dselivanov/rsparse")` but it still doesn't work. Installation log:

> devtools::install_github("dselivanov/rsparse")
Downloading GitHub repo dselivanov/rsparse@master
from URL https://api.github.com/repos/dselivanov/rsparse/zipball/master
Installing rsparse
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/kp/6kw79gtn6s54f6rz9d85ltzm0000gn/T/Rtmpn4ApQ3/devtools55964dd27359/dselivanov-rsparse-1a23602'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘rsparse’ ...
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
checking for echo... yes
checking for grep... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/private/var/folders/kp/6kw79gtn6s54f6rz9d85ltzm0000gn/T/Rtmpn4ApQ3/devtools55964dd27359/dselivanov-rsparse-1a23602':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘rsparse’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rsparse’
Installation failed: Command failed (1)

**Comment by dselivanov** [comment]
In order to be be able to install packages from source you need to isntall `xcode`: 
```sh
xcode-select --install
```
