### ISSUE TITLE
devtools::install_github("dselivanov/rsparse")  Win7 Will not compile.

### ISSUE THREAD

**Issue by jamespr615** [dselivanov/rsparse#20]
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default
 - - - - - - 
I could download and build 'float'.  
> devtools::install_github("dselivanov/float")    
it works. 

> devtools::install_github("dselivanov/rsparse")
* installing *source* package 'rsparse' ...
   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************
** libs
*** arch - i386
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.4/include" -DNDEBUG  -I"C:/Users/reefej/R/win-library/3.4/Rcpp/include" -I"C:/Users/reefej/R/win-library/3.4/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c FTRL.cpp -o FTRL.o
**In file included from C:/RBuildTools/3.4/mingw_32/i686-w64-mingw32/include/c++/random:35:0,
                 from FTRL.cpp:1:**
C:/RBuildTools/3.4/mingw_32/i686-w64-mingw32/include/c++/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the **-std=c++11 or -std=gnu++11** compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from rsparse.h:1:0,
                 from FTRL.cpp:2:

>>> I am not sure how to change settings in downloaded package.  After,  rsparse is not there. 

**HOWEVER**
Observing from another issue, 

> install.packages('githubinstall')
> library('githubinstall')
> githubinstall::gh_install_packages("rsparse", ask = FALSE, force=TRUE)

This works fine and rsparse is there. 

Oops.  No.  

I got this:
> githubinstall::gh_install_packages("rsparse", ask = FALSE, force=TRUE)

Downloading GitHub repo dgrtwo/rparse@master
from URL https://api.github.com/repos/dgrtwo/rparse/zipball/master
Installing **rparse**
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/reefej/AppData/Local/Temp/RtmpykTwMI/devtools19686420f4c/dgrtwo-rparse-bdef159" --library="C:/Users/reefej/R/win-library/3.4"  \
  --install-tests 

It then downloads into rparse.   And I cannot load the library.

**Comment by jamespr615** [comment]
Sorry to bother,  by reviewing on line and seeing various related postings,   I found the answer, mostly in your previous comments.   Here is a duplicate of workaround resolution from another thread. 

Sequence:
rsparse would not build.
Did devtools install of float.

devtools::install_github("dselivanov/float").
It built. .DLLs are present on the file system.

Could not build rsparse using devtool github install
devtools::install_github("dselivanov/rsparse")

downloaded the zip and worked to install_local

install_local("C:/Users/reefej/R/win-library/3.4/rsparse", force=TRUE)

No good. Choked on many things.

Changed the name of Makevars.in to Makevars.win
Updated Makevars.win to
SLAPACK_LIB = ${R_HOME}/bin/Rscript -e "float:::ldflags()"

PKG_CXXFLAGS = -std=c++11 $(SHLIB_OPENMP_CFLAGS) -DARMA_64BIT_WORD -O3 -fopenmp -ffast-math -march=native -mavx
PKG_LIBS = $(SHLIB_OPENMP_CFLAGS) $(SHLIB_OPENMP_CXXFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) $(SLAPACK_LIB)
CXX_STD = CXX11

It built but could not find float.dll.

I dropped both i386 and x64 version of float.dll into directory in windows path.
It found them, completed the build and I could do
library(rparse)
model = WRMF$new(rank = 8)

After Makevars updates, I expect the problem float install and build does not register the .dlls with R environment. So you have to 'show' R and windows where to find them. since the .dlls have the same name I dropped the i386 and x64 versions into separate dirs. Do not know implications at run time, but windows will find the first' one in the search path. A windows tool can tell you which gets loaded. The build knew the difference though. I will check how to 'register the float dll dirs with the R environment.

**Comment by dselivanov** [comment]
Yea, I know there some issues with autoconfigure. Unfortunately I don't have access to windows machine to figure out how to fix it. Also `float` is soft dependency for the latest versions. So you even don't need to install it.

**Comment by BigTimeStats** [comment]
Hi @jamespr615,

I followed your instructions to install and still getting a failure.

Here is what I did:
1. `devtools::install_github('dselivanov/float')` installed successfully 
2. Downloaded zip of this repo
3. Changed Makevars.win file
4. Updated path to the float .dll file which is in float package. 
`C:\Users\...xxx...\Documents\R\win-library\3.4\float\libs\x64`
I did not find the i386 file, only the x64 file.
5. Ran `devtools::install_local("rsparse-master", force=TRUE)`

Here is the error log:

```
> devtools::install_local("rsparse-master", force=TRUE)
Installing rsparse
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/...xxx.../AppData/Local/Temp/3/RtmpeG1fjR/file446058ac6cd7/rsparse-master" --library="C:/Users/...xxx.../Documents/R/win-library/3.4" --install-tests 

Installing rsparse
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/...xxx.../AppData/Local/Temp/3/RtmpeG1fjR/file44601f1f8b7/rsparse-master" --library="C:/Users/...xxx.../Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'rsparse' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -std=c++11 -fopenmp -DARMA_64BIT_WORD -O3 -fopenmp -ffast-math -march=native -mavx   -O2 -Wall  -mtune=generic -c FTRL.cpp -o FTRL.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -std=c++11 -fopenmp -DARMA_64BIT_WORD -O3 -fopenmp -ffast-math -march=native -mavx   -O2 -Wall  -mtune=generic -c FactorizationMachine.cpp -o FactorizationMachine.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -std=c++11 -fopenmp -DARMA_64BIT_WORD -O3 -fopenmp -ffast-math -march=native -mavx   -O2 -Wall  -mtune=generic -c ProductSparseDense.cpp -o ProductSparseDense.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -std=c++11 -fopenmp -DARMA_64BIT_WORD -O3 -fopenmp -ffast-math -march=native -mavx   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -std=c++11 -fopenmp -DARMA_64BIT_WORD -O3 -fopenmp -ffast-math -march=native -mavx   -O2 -Wall  -mtune=generic -c SolverAlsWrmf.cpp -o SolverAlsWrmf.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -std=c++11 -fopenmp -DARMA_64BIT_WORD -O3 -fopenmp -ffast-math -march=native -mavx   -O2 -Wall  -mtune=generic -c TopProduct.cpp -o TopProduct.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -std=c++11 -fopenmp -DARMA_64BIT_WORD -O3 -fopenmp -ffast-math -march=native -mavx   -O2 -Wall  -mtune=generic -c kmeans.cpp -o kmeans.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -std=c++11 -fopenmp -DARMA_64BIT_WORD -O3 -fopenmp -ffast-math -march=native -mavx   -O2 -Wall  -mtune=generic -c utils.cpp -o utils.o
C:/RBuildTools/3.4/mingw_64/bin/g++ -shared -s -static-libgcc -o rsparse.dll tmp.def FTRL.o FactorizationMachine.o ProductSparseDense.o RcppExports.o SolverAlsWrmf.o TopProduct.o kmeans.o utils.o -fopenmp -fopenmp -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lRblas -lgfortran -lm -lquadmath C:/PROGRA~1/R/R-34~1.3/bin/Rscript -e float:::ldflags() -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lR
g++.exe: error: C:/PROGRA~1/R/R-34~1.3/bin/Rscript: No such file or directory
no DLL was created
ERROR: compilation failed for package 'rsparse'
* removing 'C:/Users/...xxx.../Documents/R/win-library/3.4/rsparse'
In R CMD INSTALL
Installation failed: Command failed (1)
```

And session:
```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] float_0.1-2       data.table_1.11.4

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.3  R6_2.2.2        tools_3.4.3     withr_2.1.1     curl_3.1        yaml_2.1.16     memoise_1.1.0   git2r_0.21.0   
[10] digest_0.6.13   devtools_1.13.4
```

I also tried to install g++ via MinGW which also did not help: http://www.codebind.com/cprogramming/install-mingw-windows-10-gcc/ 

Path image:
![image](https://user-images.githubusercontent.com/29850965/43290054-d3f8afa4-90fa-11e8-9420-d5baf8231c9b.png)

Thank you for the help!

**Comment by jamespr615** [comment]
Right.   I never got it to build from the repository.


I installed from local zip of master repo.


https://stackoverflow.com/questions/17366772/install-r-packages-from-github-downloading-master-zip



[https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded]<https://stackoverflow.com/questions/17366772/install-r-packages-from-github-downloading-master-zip>

Install R packages from github downloading master.zip ...<https://stackoverflow.com/questions/17366772/install-r-packages-from-github-downloading-master-zip>
stackoverflow.com
I probably have some issues in my connectivity (some sort of blocks, dunno) and I can't install directly form gitHub > install_github("assertthat") Installing github repo(s) assertthat/master f...

I put the zip here

C:\Users\mrjim\R\win-library\3.4\rsparse-master.zip


I unzipped it to

rsparse-master


then I made a copy to

rsparse


and I would try to install to rsparse.  Because if it fails it deletes the target dir.  If it did that i would recopy to rsparse and try again.




________________________________

**Comment by BigTimeStats** [comment]
Gotcha, unfortunately that still did not work and getting the same error..

**Comment by jamespr615** [comment]
Ok.


If it is the problem that the linker cannot find the float.dll.

Typically I think R environment can find the .DLL in the folder of the package - cause it is registered in the R envirnoment - somehow.

I figured it could not find the float.dll because it did not get registered.

What i did was drop it into a dir windows already uses. like C:/windows/system32   and it found it.  Putting the dir in the path should work.


Looking at your log -  it says it cannoit find this directory:

C:/PROGRA~1/R/R-34~1.3/bin/Rscript:

Are the ~ a problem?

Also,  do you have rblas installed?

________________________________

**Comment by BigTimeStats** [comment]
Thanks for looking into it. I put the .dll into system32 with no luck. I added the dir to path and also didn't work. I don't have rblas installed... tried to install it with no luck, seems like other people have also struggled. 

I think the ~ are just abbreviations in the log, so I don't think that's the problem. They correspond to where all those items are located. 

At a certain point, it becomes a deep rabbit hole that's hard to get out of haha... install this/that to fix one thing in the installation chain, and just get a new error lol

Thanks!

**Comment by dselivanov** [comment]
Hey here. I'm working on fix (will allow just to use `remotes::install_github("dselivanov/rsparse")`). Hope to push it very soon.

**Comment by dselivanov** [comment]
@jamespr615 @BigTimeStats can you please try to install latest version from master with `remotes::install_github("dselivanov/rsparse")` or `devtools::install_github("dselivanov/rsparse")`  and report whether it works or not?

**Comment by jamespr615** [comment]
I will give it a try late this evening.


________________________________

**Comment by jamespr615** [comment]
I tried the download.


No luck yet.


It had to install Rtools. then rerun the command and then it chokes on Rcpp version.


I will try to install Rcpp.3.4 directly and retry.


Kick off the iinstall -

It says - package needs some dependencies and tools - do you want to install now - Yes.



It goes to install Rtools34 or Rtools35.exe


The install.package script then fails,   and the install window for Rtools35.exe comes up.


Install the Rtools from the EXE. Rerun the install devtools  install command.


Now it chokes on Rcpp version.


From the console



R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from C:/Users/reefe/Desktop/Csera/JH_DataSci/10. Capstone My Proj/.RData]

> setwd("C:/Users/reefe/Desktop/Csera/JH_DataSci/10. Capstone My Proj")
> library(devtools)
Error in library(devtools) : there is no package called ‘devtools’
> install.package('devtools')
Error in install.package("devtools") :
  could not find function "install.package"
> install.packages('devtools')
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘memoise’, ‘whisker’, ‘git2r’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/memoise_1.1.0.zip'
Content type 'application/zip' length 29957 bytes (29 KB)
downloaded 29 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/whisker_0.3-2.zip'
Content type 'application/zip' length 64940 bytes (63 KB)
downloaded 63 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/git2r_0.23.0.zip'
Content type 'application/zip' length 2810153 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.6.zip'
Content type 'application/zip' length 444097 bytes (433 KB)
downloaded 433 KB

package ‘memoise’ successfully unpacked and MD5 sums checked
package ‘whisker’ successfully unpacked and MD5 sums checked
package ‘git2r’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\reefe\AppData\Local\Temp\RtmpUlqZ0k\downloaded_packages
> library(devtools)
> devtools::install_github("dselivanov/rsparse")
Downloading GitHub repo dselivanov/rsparse@master
from URL https://api.github.com/repos/dselivanov/rsparse/zipball/master
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe'
Content type 'application/x-msdos-program' length 108622512 bytes (103.6 MB)
downloaded 103.6 MB

WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
Installation failed: Could not find build tools necessary to build rsparse
> install.packages('Rtools')
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘Rtools’ is not available (for R version 3.4.4)
> devtools::install_github("dselivanov/rsparse")
Downloading GitHub repo dselivanov/rsparse@master
from URL https://api.github.com/repos/dselivanov/rsparse/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.4.4 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
Installing rsparse
Installing 1 package: data.table
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/data.table_1.11.4.zip'
Content type 'application/zip' length 1813189 bytes (1.7 MB)
downloaded 1.7 MB

package ‘data.table’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\reefe\AppData\Local\Temp\RtmpUlqZ0k\downloaded_packages
Installing 1 package: futile.logger
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘lambda.r’, ‘futile.options’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/lambda.r_1.2.3.zip'
Content type 'application/zip' length 81372 bytes (79 KB)
downloaded 79 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/futile.options_1.0.1.zip'
Content type 'application/zip' length 17209 bytes (16 KB)
downloaded 16 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/futile.logger_1.4.3.zip'
Content type 'application/zip' length 102813 bytes (100 KB)
downloaded 100 KB

package ‘lambda.r’ successfully unpacked and MD5 sums checked
package ‘futile.options’ successfully unpacked and MD5 sums checked
package ‘futile.logger’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\reefe\AppData\Local\Temp\RtmpUlqZ0k\downloaded_packages
Installing 1 package: mlapi
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/mlapi_0.1.0.zip'
Content type 'application/zip' length 73003 bytes (71 KB)
downloaded 71 KB

package ‘mlapi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\reefe\AppData\Local\Temp\RtmpUlqZ0k\downloaded_packages
Installing 1 package: Rcpp
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rcpp_0.12.18.zip'
Content type 'application/zip' length 4424523 bytes (4.2 MB)
downloaded 4.2 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’

The downloaded binary packages are in
C:\Users\reefe\AppData\Local\Temp\RtmpUlqZ0k\downloaded_packages
Installing 1 package: RcppArmadillo
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependency ‘Rcpp’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rcpp_0.12.18.zip'
Content type 'application/zip' length 4424523 bytes (4.2 MB)
downloaded 4.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/RcppArmadillo_0.8.600.0.0.zip'
Content type 'application/zip' length 2251745 bytes (2.1 MB)
downloaded 2.1 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’
package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\reefe\AppData\Local\Temp\RtmpUlqZ0k\downloaded_packages
Installing 1 package: RhpcBLASctl
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/RhpcBLASctl_0.18-205.zip'
Content type 'application/zip' length 98843 bytes (96 KB)
downloaded 96 KB

package ‘RhpcBLASctl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\reefe\AppData\Local\Temp\RtmpUlqZ0k\downloaded_packages
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/reefe/AppData/Local/Temp/RtmpUlqZ0k/devtools2580635e1e92/dselivanov-rsparse-044231d"  \
  --library="C:/Users/reefe/Documents/R/win-library/3.4" --install-tests

ERROR: dependency 'Rcpp' is not available for package 'rsparse'
* removing 'C:/Users/reefe/Documents/R/win-library/3.4/rsparse'
In R CMD INSTALL
Installation failed: Command failed (1)
> devtools::install_github("dselivanov/rsparse")
Downloading GitHub repo dselivanov/rsparse@master
from URL https://api.github.com/repos/dselivanov/rsparse/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.4.4 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
Installing rsparse
Installing 1 package: Rcpp
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rcpp_0.12.18.zip'
Content type 'application/zip' length 4424523 bytes (4.2 MB)
downloaded 4.2 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’

The downloaded binary packages are in
C:\Users\reefe\AppData\Local\Temp\RtmpUlqZ0k\downloaded_packages
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/reefe/AppData/Local/Temp/RtmpUlqZ0k/devtools25801dd4c55/dselivanov-rsparse-044231d"  \
  --library="C:/Users/reefe/Documents/R/win-library/3.4" --install-tests

ERROR: dependency 'Rcpp' is not available for package 'rsparse'
* removing 'C:/Users/reefe/Documents/R/win-library/3.4/rsparse'
In R CMD INSTALL
Installation failed: Command failed (1)
> unistall.packages('Rcpp')
Error in unistall.packages("Rcpp") :
  could not find function "unistall.packages"
> uninstall.packages('Rcpp')
Error in uninstall.packages("Rcpp") :
  could not find function "uninstall.packages"
> uninstall('Rcpp')
Error: Can't find 'C:\Users\reefe\Desktop\Csera\JH_DataSci\10. Capstone My Proj\Rcpp'.
> remove.packages('Rcpp')
Removing package from ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Error in remove.packages : there is no package called ‘Rcpp’
> devtools::install_github("dselivanov/rsparse")
Downloading GitHub repo dselivanov/rsparse@master
from URL https://api.github.com/repos/dselivanov/rsparse/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.4.4 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
Installing rsparse
Installing 1 package: Rcpp
Installing package into ‘C:/Users/reefe/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rcpp_0.12.18.zip'
Content type 'application/zip' length 4424523 bytes (4.2 MB)
downloaded 4.2 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’

The downloaded binary packages are in
C:\Users\reefe\AppData\Local\Temp\RtmpUlqZ0k\downloaded_packages
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/reefe/AppData/Local/Temp/RtmpUlqZ0k/devtools2580477e44a/dselivanov-rsparse-044231d"  \
  --library="C:/Users/reefe/Documents/R/win-library/3.4" --install-tests

ERROR: dependency 'Rcpp' is not available for package 'rsparse'
* removing 'C:/Users/reefe/Documents/R/win-library/3.4/rsparse'
In R CMD INSTALL
Installation failed: Command failed (1)



________________________________

**Comment by dselivanov** [comment]
I'm not sure about your particular problem - it seems you have non standard R/Rtools installation. I've checked latest rsparse on win builder service and everything runs fine and passes all the tests.

**Comment by BigTimeStats** [comment]
@dselivanov thanks so much. I don't know what you did, but it seems to have worked!

Log in case it's helpful:
```
> devtools::install_github('dselivanov/rsparse')
Downloading GitHub repo dselivanov/rsparse@master
from URL https://api.github.com/repos/dselivanov/rsparse/zipball/master
Installing rsparse
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/...xxx.../AppData/Local/Temp/3/RtmpeG1fjR/devtools4460787713e4/dselivanov-rsparse-044231d" --library="C:/Users/...xxx.../Documents/R/win-library/3.4"  \
  --install-tests 

* installing *source* package 'rsparse' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -fopenmp -DARMA_32BIT_WORD -DARMA_DONT_USE_BLAS   -O2 -Wall  -mtune=generic -c FTRL.cpp -o FTRL.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -fopenmp -DARMA_32BIT_WORD -DARMA_DONT_USE_BLAS   -O2 -Wall  -mtune=generic -c FactorizationMachine.cpp -o FactorizationMachine.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -fopenmp -DARMA_32BIT_WORD -DARMA_DONT_USE_BLAS   -O2 -Wall  -mtune=generic -c ProductSparseDense.cpp -o ProductSparseDense.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -fopenmp -DARMA_32BIT_WORD -DARMA_DONT_USE_BLAS   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -fopenmp -DARMA_32BIT_WORD -DARMA_DONT_USE_BLAS   -O2 -Wall  -mtune=generic -c SolverAlsWrmf.cpp -o SolverAlsWrmf.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -fopenmp -DARMA_32BIT_WORD -DARMA_DONT_USE_BLAS   -O2 -Wall  -mtune=generic -c TopProduct.cpp -o TopProduct.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -fopenmp -DARMA_32BIT_WORD -DARMA_DONT_USE_BLAS   -O2 -Wall  -mtune=generic -c kmeans.cpp -o kmeans.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/...xxx.../Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/...xxx.../Documents/R/win-library/3.4/RcppArmadillo/include"     -fopenmp -DARMA_32BIT_WORD -DARMA_DONT_USE_BLAS   -O2 -Wall  -mtune=generic -c utils.cpp -o utils.o
C:/RBuildTools/3.4/mingw_64/bin/g++ -shared -s -static-libgcc -o rsparse.dll tmp.def FTRL.o FactorizationMachine.o ProductSparseDense.o RcppExports.o SolverAlsWrmf.o TopProduct.o kmeans.o utils.o -fopenmp -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lRblas -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lR
installing to C:/Users/...xxx.../Documents/R/win-library/3.4/rsparse/libs/x64
** R
** data
*** moving datasets to lazyload DB
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'rsparse'
    finding HTML links ... done
    FTRL                                    html  
    FactorizationMachine                    html  
    LinearFlow                              html  
    PureSVD                                 html  
    WRMF                                    html  
    ap_k                                    html  
    movielens100k                           html  
    soft_impute                             html  
    train_test_split                        html  
** building package indices
** testing if installed package can be loaded
* DONE (rsparse)
In R CMD INSTALL
> library(rsparse)
Setting OpenMP threads number to 48. 
Can be adjusted by setting `options("rsparse_omp_threads" = N_THREADS)`
```

**Comment by dselivanov** [comment]
Perfect!

**Comment by jamespr615** [comment]
It was my foolishness.


________________________________
