### ISSUE TITLE
Classification Using Factorization Machines

### ISSUE THREAD

**Issue by ThakurRajAnand** [dselivanov/rsparse#21]
Thank you for this great package. Somehow, FM is not returning the probabilities for a classification problem and I can't find any parameter to force that as well. Please have a look at my code below and let me know if I am missing something
```R
fm <- FactorizationMachine$new(learning_rate_w = learning_rate, rank = rank, lambda_w = lambda1, lambda_v = lambda2, task = "classification", intercept = TRUE, learning_rate_v = learning_rate)
fm$fit(trainSparse, target, n_iter = iter)
pred <- fm$predict(testSparse)
```
Code runs without any issues but returns class.

**Comment by dselivanov** [comment]
@ThakurRajAnand could you provide reproducible example? for example using `movie_review` data from text2vec - http://text2vec.org/vectorization.html ?

**Comment by dselivanov** [comment]
Not reproducible
