### ISSUE TITLE
future float R version dependency

### ISSUE THREAD

**Issue by wrathematics** [dselivanov/rsparse#24]
Just a heads up, but in v3.6.0 of R, they are changing some Make macros that affect float. I believe the expectation is that to comply, I will need to submit an update soon using the new macros, and an R (>= 3.6.0) dependency.

I try to support pretty old versions of R so I'm not thrilled about this. Unfortunately I don't think there's any way avoid it. Hopefully this doesn't impact you too much.

**Comment by wrathematics** [comment]
Forgot: this shouldn't affect your configure scripts or anything. It's a Fortran thing that is affecting float (because I have to ship the reference code, which is written in Fortran). Basically it just creates a >= 3.6.0 dependency for you (via float).

**Comment by dselivanov** [comment]
Thanks for the notification. Not an issue for me since rsparse is pretty
new pkg with almost zero user base :-)

пн, 22 апр. 2019 г., 21:54 Drew Schmidt <notifications@github.com>:
